### ISSUE TITLE
Update multipart download to channel to a single threaded write

### ISSUE THREAD

**Issue by nhibberd** [ambiata/mismi#102]

**Comment by olorin** [comment]
Is this a "we know this is faster and just need to implement it" thing or a "we need to implement this to determine if it's faster" thing?

**Comment by nhibberd** [comment]
This is:
Current multipart download is cpu bounded. Need to investigate if its in the c code or somewhere in amazonka (@jystic had some debugging things)

**Comment by markhibberd** [comment]
@nhibberd Isn't it uploaded that is cpu bounded? I think this one was a little clear cut. Current implementation is :100: on ssd and :-100: on spinning disks?

**Comment by markhibberd** [comment]
(smimilar issues though, and I think it is a little bit of both)

**Comment by nhibberd** [comment]
Sorry yeah misread title, Yeah thats correct. Basic idea was to implement and check performance on ssds is still :100:

**Comment by olorin** [comment]
Do we have old benchmark results stored anywhere?

**Comment by nhibberd** [comment]
Not sure what that means, what kind of results

**Comment by olorin** [comment]
Just wondering if there are existing benchmark results with multithreaded writes which could be used as a baseline for testing changes? Will create some if not.

**Comment by nhibberd** [comment]
Still not really clear what were classifying as 'benchmark results'. Usually practice to allocate a 10gb file and upload/download ~10x

**Comment by olorin** [comment]
Okay, thanks. (Ftr, what I mean by "benchmark results" is data from any controlled, reproducible test.)

**Comment by nhibberd** [comment]
This is fairly outdated now, but we did have this - https://github.com/ambiata/mismi/blob/master/mismi-s3/doc/benchmarks.md

**Comment by nhibberd** [comment]
Really need instance type on this as well now

**Comment by nhibberd** [comment]
From memory. 
On rust: python is twice as fast as mismi
on ssd: mismi is about 6-8x as fast as python
