### ISSUE TITLE
Copy in constant space

### ISSUE THREAD

**Issue by charleso** [ambiata/mismi#151]
Currently `copy` doesn't run in constant memory. This may not necessarily be a problem for now, but some notes if we do decide to tackle this.

1. Discard the results immediately. Currently this is a lazy list of units. Instead we should introduce something (like) the following, which can either stop on a monad bind, or return unit:
    
    `waitForNResults_ :: Int -> Chan (m a) -> m ()`
2. Put back pressure on the conduit listing, with something like:
    
    `spin :: m Bool -> Conduit i m o`
    
    Which would then require keeping track of the list elements processed. A data structure like the following may help:
    
     `(MVar Int, Chan x)`

Some related perf results:

https://github.com/ambiata/mismi/issues/150

**Comment by nhibberd** [comment]
Can we close this now @charleso

**Comment by charleso** [comment]
:+1:
