### ISSUE TITLE
EnvError needs to include a parse failure data type

### ISSUE THREAD

**Issue by nhibberd** [ambiata/mismi#194]
https://github.com/ambiata/mismi/blob/master/mismi-core/src/Mismi/Environment.hs#L41-L43

Runnning with `AWS_DEFAULT_REGION=ap-southeast-2a` errors with the following messages `Environment variable AWS_DEFAULT_REGION was not found`

**Comment by markhibberd** [comment]
Assuming it is just meant to say ap-southeast-2a is not a valid region?

**Comment by nhibberd** [comment]
Yea, I feel like that is a reasonable error
