### ISSUE TITLE
Multipart upload sequential read

### ISSUE THREAD

**Issue by nhibberd** [ambiata/mismi#252]

**Comment by nhibberd** [comment]
Current multipart upload is cpu bounded. Need to investigate if its in the c code or somewhere in amazonka (@jystic had some debugging things)

**Comment by olorin** [comment]
Do you have a test case I can use to reproduce?

**Comment by nhibberd** [comment]
Upload any file using multipart upload (> 100mb)

**Comment by olorin** [comment]
It's split between GC and TLS computations, TLS being the more significant of the two. ~3.5% of total cycles are in C (specifically, `cryptonite_aesni_gcm_encrypt128`); the rest of the TLS stuff is Haskell (various Network.TLS symbols). The GC overhead is around 40%, which isn't -that- bad considering how much allocation is involved; total alloc is around 22GiB for 3.4GiB of data, which could probably be cut down a bit but I'm not sure it'd make a big enough difference to be worthwhile.

Can push ~200Mb with mismi, cf ~600Mb with Python, so definitely improvements to be made. First place to look is network-tls, though seeing if we can reduce allocation somewhat might be sensible also; didn't get much further than that.

**Comment by olorin** [comment]
Also interesting: `aws` is seeing ~3x as many page faults as `s3` plus a higher percentage of cycles spent in kernelspace (around double as a ratio of total cycles). mismi also does a little better on context switches.
