### ISSUE TITLE
Possible issue with multipart download and retries

### ISSUE THREAD

**Issue by domdere** [ambiata/mismi#270]
I haven't checked yet which version of `mismi-s3` i am using yet, so not sure if its an issue that has been fixed,

but i am getting an issue where it definitely looks like i am hanging on a multipart download call, my app has hung and when i look at its open file descriptors:

``` Shell
ls -lhrt /proc/16939/fd
total 0
lrwx------. 1 ** ** 64 Dec 15 07:07 9 -> [eventfd]
l-wx------. 1 ** ** 64 Dec 15 07:07 8 -> pipe:[279072]
lr-x------. 1 ** ** 64 Dec 15 07:07 7 -> pipe:[279072]
lrwx------. 1 ** ** 64 Dec 15 07:07 6 -> [eventfd]
l-wx------. 1 ** ** 64 Dec 15 07:07 5 -> pipe:[279071]
lr-x------. 1 ** ** 64 Dec 15 07:07 4 -> pipe:[279071]
lrwx------. 1 ** ** 64 Dec 15 07:07 3 -> [eventpoll]
l-wx------. 1 ** ** 64 Dec 15 07:07 2 -> pipe:[279067]
l-wx------. 1 ** ** 64 Dec 15 07:07 197 -> /mnt/**/********/work/********.f6057cf1-ea5e-49f4-9a42-031467b84664
lrwx------. 1 ** ** 64 Dec 15 07:07 174 -> socket:[279352]
lrwx------. 1 ** ** 64 Dec 15 07:07 12 -> socket:[279053]
lrwx------. 1 ** ** 64 Dec 15 07:07 10 -> socket:[31092]
l-wx------. 1 ** ** 64 Dec 15 07:07 1 -> pipe:[279067]
lrwx------. 1 ** ** 64 Dec 15 07:07 0 -> /dev/pts/1
```

It looks like its hung on one last part with `197`, the file was approximate 20GB and unfortunately i didnt have any debug logging turned on but it seems intermittent in that if i run it again it succeeds so it sounds pretty related to retries, which i understand had been modified lately, i'll check the version tomorrow and if its just a matter of bumping the version i'll close the issue

**Comment by olorin** [comment]
If it happens again, could you grab an strace? `strace -o mismi.strace -fp $s3_pid`

**Comment by domdere** [comment]
oh man i didnt realise we had `strace` on our machines now, i vaguely remember trying it once and finding it wasnt there

yeah i'll definitely do that next time

**Comment by olorin** [comment]
Yeah, I missed my standard diagnostic tools pretty sorely in my first week; I put it and a bunch of similar things in the kit manifest (strace, ltrace, lsof, perf, tcpdump, iftop, et cetera), should be deployed everywhere now.
