### ISSUE TITLE
Problems with HsOpenSSL and libssl-1.1

### ISSUE THREAD

**Issue by erikd-ambiata** [ambiata/mismi#352]
I'm running Debian testing on my dev machine and that has OpenSSL version 1.1.x.

The OpenSSL project is trying to fix 20 years worth of busted and hence breaking some APIs which in turn causes breakage for [HsOpenSSL](https://github.com/vshabanov/HsOpenSSL/issues/16).

This ticket is really just to note the problem here in case anyone else runs into it. For me the current solution is to work in a Debian stable chroot, but that will probably stop working when the current testing release transitions to stable (expected some time this year).

**Comment by vshabanov** [comment]
Hi! HsOpenSSL maintainer is here. If you have some test cases where HsOpenSSL is not working with OpenSSL 1.1.x feel free to open an issue.

**Comment by erikd-ambiata** [comment]
I did. It was this issue https://github.com/vshabanov/HsOpenSSL/issues/16 which you have now fixed. Thanks!

**Comment by vshabanov** [comment]
Oh, that's great! Haven't thought that @erikd and @erikd-ambiata is the same person )

**Comment by erikd-ambiata** [comment]
Yeah, its my personal account and my work account :). Its just easier to keep the two separate.

**Comment by erikd-ambiata** [comment]
I've now successfully built the mismi-openssl package against HsOpenSSL 0.11.4.1.

Probably not worth increasing the lower bound in the cabal file just for this because so few people are running Debian Testing.
